[package]
name = "duet-app"
version = "0.3.1"
description = "An opinionated design tool, built by designers, for designers. You and your AI work hand in hand on one canvas."
authors = ["Sourish Mazumdar"]
license = "PolyForm-Shield-1.0.0"
repository = "https://github.com/justsourish/duet"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "duet_app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-dialog = "2.8.1"
git2 = { version = "0.21.0", default-features = false, features = ["vendored-libgit2"] }
tiny_http = "0.12.0"
uuid = { version = "1.27.0", features = ["v4"] }
base64 = "0.23.1"
zip = { version = "2", default-features = false, features = ["deflate"] }


# Read the optimization guideline for more details: https://tauri.app/concept/size/#cargo-configuration
[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true
